### ISSUE TITLE
As a guest, I can sign up for an account

### ISSUE THREAD

**Issue by cmacaulay** [cmacaulay/folio-share#11]
As a guest user,
When I visit the root path and select “create account” 
When I fill in the sign-up information
I can create a registered user account

**Comment by cmacaulay** [comment]
As a guest, when I click "create account"
-- I am redirected to the create account page 
-- I can enter in my information

**Comment by s-espinosa** [comment]
Seems to be a bug here of some sort when I try to create a second account. Maybe it's because I used some duplication. Before moving this card, would like the following implemented:

* More descriptive error messages in the flash to tell me what I've done wrong (is there a validation on uniqueness for phone? minimum number of characters for username? I don't need these things, but couldn't figure out why I couldn't create a second user).
* Password field changed to not expose password as I'm typing.

**Comment by cmacaulay** [comment]
@s-espinosa I will update waffle. We are aware the client wants some warning messages, it just wasn't a priority over some of the base functionality this weekend. I can pump this up in priority!

**Comment by s-espinosa** [comment]
@cmacaulay Thanks! I'm not marking these comments based on urgency, but just things I'm noting before I move cards. Want to make sure that we're not losing functionality by moving cards prematurely. I'm sure you'll be getting a bunch of notes as I move through these.
